name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODNiODJiZDUtMDllNi00ODgxLTg4MDQtNzM0M2IzYjA4Y2Y4IiwidGVuYW50X2lkIjoiOTAwOTgzMjBjNzJhZTBlMjkxYjE3MWM1NzEzNTRjZmZkNWY1NmIxYjI4ZjA5NjY5NDc3YTgzMjI2ODUyOGZjMCIsImludGVybmFsX3NlY3JldCI6IjIxODgxZWNiLWZkNDEtNGViZS1hZDdiLTc2OTI0NDJlY2Q5YyJ9.5ONowYhbGsJRvwxhpgu_V0-V5TxpzCgm83vUQV9Ra1U"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"